### ISSUE TITLE
Down loading the dataset

### ISSUE THREAD

**Issue by qingchenkanlu** [zubair-irshad/CenterSnap#7]
Thanks for your sharing! The dataset is hard for me to download, it is too large, is there any other way to download it? I will be appreciate if you can seperate the training dataset into a series of parts.

**Comment by zubair-irshad** [comment]
Thanks for your interest in our work. We do not plan on releasing the dataset into parts. I would recommend using a download accelerator/download manager to download the CAMERA dataset. We might consider releasing a small subset of the training data to get started (although we recommend training on the complete data for reported paper performance).

To get started / explore the CenterSnap model, please feel free to look at our [colab notebook](https://colab.research.google.com/github/zubair-irshad/CenterSnap/blob/master/notebook/explore_CenterSnap.ipynb) or download the [Real data](https://github.com/zubair-irshad/CenterSnap#-dataset) and train on it. Due to the real data being small in size, we recommend following the complete [training procedure](https://github.com/zubair-irshad/CenterSnap#-training-and-inference) for most optimal results i.e. train on synthetic and fine tune on real.

**Comment by qingchenkanlu** [comment]
OK，thanks！
